self.addEventListener('fetch', function (event) {
  event.respondWith(
    caches.match(event.request).then(function (response) {
      return response || fetch(event.request);
    })
  );
});

self.addEventListener('install', function (e) {
  e.waitUntil(
    caches.open('psysa2020-cache').then(function (cache) {
      return cache.addAll([
        '/',
        '/yearbook/',
        '/gallery',
        '/extra/',
        '/confessions/',
        '/teachers/',
        '/icon-192.png',
        '/manifest.json',
        '/confessions/index.html',
        '/confessions/assets/images/confessions.png',
        '/confessions/assets/css/style.css',
        '/confessions/assets/js/index.js',
        '/confessions/assets/js/confessions.js',
        '/site.js',
        '/yearbook/index.html',
        '/yearbook/assets/images/yearbooktext.png',
        '/yearbook/assets/images/display_pictures/44.jpg',
        '/yearbook/assets/images/display_pictures/51.jpg',
        '/yearbook/assets/images/display_pictures/34.jpg',
        '/yearbook/assets/images/display_pictures/49.jpg',
        '/yearbook/assets/images/display_pictures/55.jpg',
        '/yearbook/assets/images/display_pictures/7.jpg',
        '/yearbook/assets/images/display_pictures/29.jpg',
        '/yearbook/assets/images/display_pictures/12.jpg',
        '/yearbook/assets/images/display_pictures/46.jpg',
        '/yearbook/assets/images/display_pictures/53.jpg',
        '/yearbook/assets/images/display_pictures/42.jpg',
        '/yearbook/assets/images/display_pictures/48.jpg',
        '/yearbook/assets/images/display_pictures/61.jpg',
        '/yearbook/assets/images/display_pictures/10.jpg',
        '/yearbook/assets/images/display_pictures/63.jpg',
        '/yearbook/assets/images/display_pictures/45.jpg',
        '/yearbook/assets/images/display_pictures/43.jpg',
        '/yearbook/assets/images/display_pictures/1.jpg',
        '/yearbook/assets/images/display_pictures/9.jpg',
        '/yearbook/assets/images/display_pictures/20.jpg',
        '/yearbook/assets/images/display_pictures/14.jpg',
        '/yearbook/assets/images/display_pictures/19.jpg',
        '/yearbook/assets/images/display_pictures/38.jpg',
        '/yearbook/assets/images/display_pictures/65.jpg',
        '/yearbook/assets/images/display_pictures/3.jpg',
        '/yearbook/assets/images/display_pictures/52.jpg',
        '/yearbook/assets/images/display_pictures/33.jpg',
        '/yearbook/assets/images/display_pictures/2.jpg',
        '/yearbook/assets/images/display_pictures/11.jpg',
        '/yearbook/assets/images/display_pictures/67.jpg',
        '/yearbook/assets/images/display_pictures/17.jpg',
        '/yearbook/assets/images/display_pictures/57.jpg',
        '/yearbook/assets/images/display_pictures/5.jpg',
        '/yearbook/assets/images/display_pictures/24.jpg',
        '/yearbook/assets/images/display_pictures/15.jpg',
        '/yearbook/assets/images/display_pictures/36.jpg',
        '/yearbook/assets/images/display_pictures/59.jpg',
        '/yearbook/assets/images/display_pictures/54.jpg',
        '/yearbook/assets/images/display_pictures/31.jpg',
        '/yearbook/assets/images/display_pictures/21.jpg',
        '/yearbook/assets/images/display_pictures/16.jpg',
        '/yearbook/assets/images/display_pictures/6.jpg',
        '/yearbook/assets/images/display_pictures/41.jpg',
        '/yearbook/assets/images/display_pictures/26.jpg',
        '/yearbook/assets/images/display_pictures/25.jpg',
        '/yearbook/assets/images/display_pictures/47.jpg',
        '/yearbook/assets/images/display_pictures/62.jpg',
        '/yearbook/assets/images/display_pictures/32.jpg',
        '/yearbook/assets/images/display_pictures/60.jpg',
        '/yearbook/assets/images/display_pictures/4.jpg',
        '/yearbook/assets/images/display_pictures/37.jpg',
        '/yearbook/assets/images/display_pictures/64.jpg',
        '/yearbook/assets/images/display_pictures/30.jpg',
        '/yearbook/assets/images/display_pictures/13.jpg',
        '/yearbook/assets/images/display_pictures/27.jpg',
        '/yearbook/assets/images/display_pictures/23.jpg',
        '/yearbook/assets/images/display_pictures/22.jpg',
        '/yearbook/assets/images/display_pictures/58.jpg',
        '/yearbook/assets/images/display_pictures/50.jpg',
        '/yearbook/assets/images/display_pictures/40.jpg',
        '/yearbook/assets/images/display_pictures/56.jpg',
        '/yearbook/assets/images/display_pictures/39.jpg',
        '/yearbook/assets/images/display_pictures/35.jpg',
        '/yearbook/assets/images/display_pictures/28.jpg',
        '/yearbook/assets/images/display_pictures/8.jpg',
        '/yearbook/assets/images/display_pictures/18.jpg',
        '/yearbook/assets/images/display_pictures/66.jpg',
        '/yearbook/assets/images/kuri.jpg',
        '/yearbook/assets/css/style.css',
        '/yearbook/assets/js/index.js',
        '/yearbook/assets/js/quotes.js',
        '/icon-512.png',
        '/gallery/index.html',
        '/gallery/assets/images/Gallery/one/9 May 2017 - End of Sem 2.jpg',
        '/gallery/assets/images/Gallery/one/25 Nov 2016 - End of Sem 1.jpg',
        '/gallery/assets/images/Gallery/one/25 Nov 2016 - Mannequin Challenge.mp4',
        '/gallery/assets/images/Gallery/one/16 Mar 2017 - Adarsh_s epic party popper fail.mp4',
        '/gallery/assets/images/Gallery/one/9 May 2017 - Undampoori.jpg',
        '/gallery/assets/images/Gallery/one/1 Aug 2016 - MEC First Day (Orientation).jpg',
        '/gallery/assets/images/Gallery/one/16 Mar 2017 - Farewell Adharsh Sir.jpg',
        '/gallery/assets/images/Gallery/one/9 May 2017 - Sem End gif.mp4',
        '/gallery/assets/images/Gallery/one/4 May 2017 - Farewell Jumana Miss.jpg',
        '/gallery/assets/images/Gallery/one/16 Mar 2017 - Adharsh Sir Farewell gift.jpg',
        '/gallery/assets/images/Gallery/four/13 Oct 2019 - Green Mile.jpg',
        '/gallery/assets/images/Gallery/four/10 Mar 2020 - Holi Hai (Last day).jpg',
        '/gallery/assets/images/Gallery/four/19 Jan 2020 - Steve_s brother_s wedding.jpg',
        '/gallery/assets/images/Gallery/four/7 Mar 2020 - Dhruva After Party.JPG',
        '/gallery/assets/images/Gallery/four/9 Sep 2019 - Midu_s sister_s wedding.jpg',
        '/gallery/assets/images/Gallery/four/6 Jan 2020 - Adheep_s brother_s wedding.jpg',
        '/gallery/assets/images/Gallery/four/16 Feb 2020 - Meenakshi_s brother_s wedding.jpg',
        '/gallery/assets/images/Gallery/four/27 Aug 2019 - Anjali Miss Farewell.jpg',
        '/gallery/assets/images/Gallery/four/14 Jan 2020 - Dhruva.jpg',
        '/gallery/assets/images/Gallery/four/7 Sep 2019 - Onam.jpg',
        '/gallery/assets/images/Gallery/four/25 Oct 2019 - NBA Cleaning.jpg',
        '/gallery/assets/images/Gallery/four/28 Oct 2019 - Chaithanya Miss Farewell.jpg',
        '/gallery/assets/images/Gallery/four/14 Jan 2020 - Arts Inauguration.jpg',
        '/gallery/assets/images/Gallery/four/3 Jan 2020 - PsySA.jpg',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Namdroling Monastery, Coorg.jpg',
        '/gallery/assets/images/Gallery/five/21 Mar 2019 - Golden hour!.jpg',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Bamboo Forest, Coorg Song.mp4',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Psy Psy Psy.mp4',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Bamboo Forest, Coorg.JPG',
        '/gallery/assets/images/Gallery/five/23 Mar 2019 - A+.jpg',
        '/gallery/assets/images/Gallery/five/21 Mar 2019 - St.Mary_s Island.jpg',
        '/gallery/assets/images/Gallery/five/22 Mar 2019 - Belur.jpg',
        '/gallery/assets/images/Gallery/five/21 Mar 2019 - Malpe.jpg',
        '/gallery/assets/images/Gallery/five/21 Mar 2019 - Udupi Hotel.jpeg',
        '/gallery/assets/images/Gallery/five/23 Mar 2019 - Chikmagalur.jpg',
        '/gallery/assets/images/Gallery/five/20 Mar 2019 - Dinner in Thrissur.JPG',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Bamboo Forest, Coorg.jpg',
        '/gallery/assets/images/Gallery/five/21 Mar 2019 - Holi hai!.jpg',
        '/gallery/assets/images/Gallery/five/24 Mar 2019 - Bamboo Forest, Coorg.mp4',
        '/gallery/assets/images/Gallery/two/9 Feb 2018 - Girls Lunch - Mallu_s Dhaba.jpg',
        '/gallery/assets/images/Gallery/two/19 Dec 2017 - End of Sem 3.JPG',
        '/gallery/assets/images/Gallery/two/11 Mar 2018 - Vagamon.jpg',
        '/gallery/assets/images/Gallery/two/12 Apr 2018 - End Of Sem 4.jpg',
        '/gallery/assets/images/Gallery/two/11 Mar 2018 - Bamboo Forest Boys.jpg',
        '/gallery/assets/images/Gallery/two/30 Aug 2017 - Onam 2017 Bijumon Sir.jpg',
        '/gallery/assets/images/Gallery/two/30 Aug 2017 - Onam 2017 Girls.JPG',
        '/gallery/assets/images/Gallery/two/30 Aug 2017 - Onam 2017.JPG',
        '/gallery/assets/images/Gallery/two/30 Aug 2017 - Onam 2017 Amphi.png',
        '/gallery/assets/images/Gallery/two/11 Mar 2018 - Bamboo Forest.jpg',
        '/gallery/assets/images/Gallery/two/28 Jun 2018 - End of Sem 4 Exams.jpg',
        '/gallery/assets/images/Gallery/two/11 Mar 2018 - Vagamon Boys.jpg',
        '/gallery/assets/images/Gallery/two/28 Jun 2018 - Dab! Dab! Dab!.mp4',
        '/gallery/assets/images/Gallery/three/22 Nov 2018 - It_s nap time!.jpg',
        '/gallery/assets/images/Gallery/three/17 Oct 2018 - Girls @ Kuzhupilly.jpg',
        '/gallery/assets/images/Gallery/three/28 Mar 2019 - IV After-effects.mp4',
        '/gallery/assets/images/Gallery/three/27 Jan 2019 - Jimmy_s brother_s wedding.jpg',
        '/gallery/assets/images/Gallery/three/28 Nov 2018 - Angel Miss Class Tino Singing.mp4',
        '/gallery/assets/images/Gallery/three/6 Aug 2018 - Farewell Bijumon Sir.jpg',
        '/gallery/assets/images/Gallery/three/30 Nov 2018 - Girls day out.jpg',
        '/gallery/assets/images/Gallery/three/28 Mar 2019 - IV After-effects.jpg',
        '/gallery/assets/images/Gallery/three/15 Jun 2019 - End of sem 6.jpg',
        '/gallery/assets/images/Gallery/three/28 Nov 2018 - Jithin Nille Nille.mp4',
        '/gallery/assets/images/Gallery/three/27 Apr 2019 - Adrian_s sister_s wedding.jpg',
        '/gallery/assets/images/gallery.png',
        '/gallery/assets/css/style.css',
        '/gallery/assets/js/index.js',
        '/gallery/assets/js/gallery.js',
        '/index.html',
        '/teachers/index.html',
        '/teachers/assets/images/Teacher Photos/Jaimon.jpg',
        '/teachers/assets/images/Teacher Photos/Remadevi.jpg',
        '/teachers/assets/images/Teacher Photos/Priya2.jpg',
        '/teachers/assets/images/Teacher Photos/Jumana.jpg',
        '/teachers/assets/images/Teacher Photos/Manu.jpg',
        '/teachers/assets/images/Teacher Photos/Mahesh.jpg',
        '/teachers/assets/images/Teacher Photos/Priya.jpg',
        '/teachers/assets/images/Teacher Photos/Angel.jpg',
        '/teachers/assets/images/Teacher Photos/Sarath.jpg',
        '/teachers/assets/images/Teacher Photos/Jimmy.jpg',
        '/teachers/assets/images/Teacher Photos/Sinu.jpg',
        '/teachers/assets/images/Teacher Photos/Manilal.jpg',
        '/teachers/assets/images/Teacher Photos/Sreekumar.jpg',
        '/teachers/assets/images/Teacher Photos/Reshma.jpg',
        '/teachers/assets/images/Teacher Photos/Krishnadas.jpg',
        '/teachers/assets/images/Teacher Photos/Martina.jpg',
        '/teachers/assets/images/Teacher Photos/Justin.jpg',
        '/teachers/assets/images/Teacher Photos/Sindhu.jpg',
        '/teachers/assets/images/Teacher Photos/Lekshmi.jpg',
        '/teachers/assets/images/Teacher Photos/Lomin.jpg',
        '/teachers/assets/images/Teacher Photos/Sarayu.jpg',
        '/teachers/assets/images/Teacher Photos/Divya.jpg',
        '/teachers/assets/images/Teacher Photos/Raheena.jpg',
        '/teachers/assets/images/Teacher Photos/Kiran.jpg',
        '/teachers/assets/images/Teacher Photos/Preena.jpg',
        '/teachers/assets/images/Teacher Photos/Sheena.jpg',
        '/teachers/assets/images/Teacher Photos/Anjali.jpg',
        '/teachers/assets/images/Teacher Photos/Bijumon.jpg',
        '/teachers/assets/images/Teacher Photos/Jiby.jpg',
        '/teachers/assets/images/Teacher Photos/Sajeesh.jpg',
        '/teachers/assets/images/Teacher Photos/Jisha.jpg',
        '/teachers/assets/images/Teacher Photos/Adharsh.jpg',
        '/teachers/assets/images/Teacher Photos/Chaithanya.JPG',
        '/teachers/assets/images/Teacher Photos/Vineetha.jpg',
        '/teachers/assets/images/Teacher Photos/Alice.jpg',
        '/teachers/assets/images/Teacher Photos/Thushara.jpg',
        '/teachers/assets/images/Teacher Photos/Suja.jpg',
        '/teachers/assets/images/Teacher Photos/Anjana.jpg',
        '/teachers/assets/images/Teacher Photos/Remya.jpg',
        '/teachers/assets/images/Teacher Photos/Fymin.jpg',
        '/teachers/assets/images/ourteachers.png',
        '/teachers/assets/css/style.css',
        '/teachers/assets/js/index.js',
        '/teachers/assets/js/quotes.js',
        '/extra/index.html',
        '/extra/assets/images/darrow.png',
        '/extra/assets/images/wreath.png',
        '/extra/assets/images/Memes/Meme8.jpg',
        '/extra/assets/images/Memes/Meme1.png',
        '/extra/assets/images/Memes/Meme10.jpg',
        '/extra/assets/images/Memes/Meme11.jpg',
        '/extra/assets/images/Memes/Meme2.jpg',
        '/extra/assets/images/Memes/Meme17.jpg',
        '/extra/assets/images/Memes/Meme7.jpg',
        '/extra/assets/images/Memes/Meme3.jpg',
        '/extra/assets/images/Memes/Meme6.jpg',
        '/extra/assets/images/Memes/Meme16.jpeg',
        '/extra/assets/images/Memes/Meme12.jpeg',
        '/extra/assets/images/Memes/Meme13.jpg',
        '/extra/assets/images/Memes/Meme5.jpeg',
        '/extra/assets/images/Memes/Meme18.jpg',
        '/extra/assets/images/Memes/Meme15.jpg',
        '/extra/assets/images/Memes/Meme14.jpeg',
        '/extra/assets/images/Memes/Meme4.jpeg',
        '/extra/assets/images/extra.png',
        '/extra/assets/css/style.css',
        '/extra/assets/js/analyticsContent.js',
        '/extra/assets/js/index.js',
        '/extra/assets/js/paragraphs.js',
        '/extra/assets/js/graph_data/most_media.json',
        '/extra/assets/js/graph_data/talking_day.json',
        '/extra/assets/js/graph_data/talking_hrs.json',
        '/extra/assets/js/graph_data/popular_words.json',
        '/extra/assets/js/graph_data/most_emoji.json',
        '/extra/assets/js/graph_data/semwise_talk.json',
        '/extra/assets/js/graph_data/talking_months.json',
        '/extra/assets/js/graph_data/most_del_msg.json',
        '/extra/assets/js/graph_data/who_talked_most.json',
        '/extra/assets/js/memes.js',
        '/extra/assets/js/awards.js',
        '/extra/assets/js/graphs.js',
        '/assets/images/210.png',
        '/assets/images/psysa.mp4',
        '/assets/images/favicon.png',
        '/assets/css/style.css',
        '/assets/css/navbar.css',
      ]);
    })
  );
});